name: Deploy

on:
  push:
    branches:
      - master
jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      - env: 
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Deploy backend to heroku
        run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<heroku-project>.git master
 
